# Generated by Django 4.1.6 on 2023-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='icon',
            field=models.CharField(default=30, max_length=100),
            preserve_default=False,
        ),
    ]
