# Generated by Django 4.1.6 on 2023-04-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cards_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='icon',
        ),
    ]
