# Generated by Django 4.1.6 on 2023-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='infoo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
